Version 1
GorbunovaVI/mp2-lab1-set pull request #1
Opened 2019-09-24 09:22 UTC by GorbunovaVI

2019-09-27 15:31 UTC, alvls requested changes

2019-09-27 15:31 UTC, alvls commented on src/tbitfield.cpp
> +		MemLen = (len - 1) / (sizeof(TELEM) * 8) + 1;
Почему память выделяется до того, как станет известен размер? В результате тесты падают и программа-пример тоже! Исправьте

2019-09-29 17:06 UTC, alvls commented
Валерия, один методы вы исправили. А остальные?

2019-09-29 17:23 UTC, GorbunovaVI commented on src/tbitfield.cpp
> +		MemLen = (len - 1) / (sizeof(TELEM) * 8) + 1;
Здравсвуйте,в остальных методах память выделяется после размера.
В первом методе я случайно поменяла местами эти две строки(хотела поменять другие),потому что гит не хотел выгружать в новый pull request программу без изменений.

2019-09-29 17:35 UTC, alvls commented on src/tbitfield.cpp
> +		MemLen = (len - 1) / (sizeof(TELEM) * 8) + 1;
Я имел ввиду, что нужно исправить остальные красные тесты

2019-09-29 19:10 UTC, GorbunovaVI commented on src/tbitfield.cpp
> +		MemLen = (len - 1) / (sizeof(TELEM) * 8) + 1;
Исправила методы,все тесты проходят

2019-09-29 20:09 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество проектирования: | 2,0
Качество   кода: | 2,0
Бонус: | 0,0
Штраф: | 1,0
__Итого:__ | 7,0

2019-09-29 20:10 UTC, merged